### ISSUE TITLE
Action to be taken with respect to RHOC trading not honoring Pithia and Barcelona RHOC (was pithia action)

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/sm19a#12]
Greg suggested the special meeting consider axtion with respect to  the Pithia failure to fulfil contract terms. It is not clear we can make any decision without disclosing confidential information but we can help the coop by providing community sentiment that may help guide the board. Actions can be considered with respect to policy regarding Pithia RHOC.

**Comment by jimscarver** [comment]
Presuming that pithia will be liable for the value of the rhoc I suggest we allow pithia to sell or invest their rhoc while we pursue recovery of the value derived.

I am not gravely concerned about them flooding the market with rhoc. RHOC holders have a stake in rchain and it would be a crime if any happened to receive worthless rhoc.

**Comment by dckc** [comment]
Can you think of anyone in a position to make a useful next step on this, @jimscarver? I'm giving you the ball, for now.

Let's try to turn the corner from brainstorming to actually tracking issues to resolution.

**Comment by richjensen3000** [comment]
I believe legal action has been filed. Tracking might start by coming up to speed on the documents filed, etc.  I will put this at the top of AFC restart.

**Comment by jimscarver** [comment]
The tainted rhoc has been sanctioned and rhoc trading on kucoin disabled. Greg's advise is to not buy rhoc on other exchanges because it could be worthless. The coop effectively halted rhoc trading which will not sit well with some rhoc holders.

The coop could create a tradable rhol token on ethereum which could be obtained one for one with non-tainted rhoc. For every rhol created a rhoc would be burned. Rhol's could be good forever for rev in the rchain wallet. Rhol could provide the REV market on ethereum and fund cross chain transactions.

Rhoc sent to the contract could trigger an event spawning a process to determine the validity of the rhoc. The contract owner then would be triggered to initiate the conversion, send back or hold the rhoc.

I feel we have a responsibility to enable rhoc trading both for those who need to trade and those who might buy. It would enable the rhoc as rhol to recover in value. 

If there is interest I am willing to spend some time on this.

**Comment by jimscarver** [comment]
With trading suspended on kucoin perhaps we should consider creating our own exchange on ethereum where members and others supporters can deposit rhoc verified to be legal supported by fees. 0x, oasis and other open source exchanges could be considered. It might be run by some SPV if there is interest.

**Comment by jimscarver** [comment]
A members only discord server might provide for RHOC trading among trusted members. Anyone trusted by the community could run such a server. Membership could be by invitation only.

**Comment by fweilih** [comment]
Hi Jim, do you think it is appropriate to gauge and communicate community sentiment, without those expressing their sentiments having knowledge of all relevant facts?  I question if the necessity for confidentiality is being used too widely here.  I am not trying to challenge, just question.  I have always found your comments thoughtful and considered, BTW.  Thanks.

**Comment by jimscarver** [comment]
Hi @fweilih, Pure democracy tends to make poor decisions. Who should make a decision should be considered. [Liquid democracy with a trust metric](https://docs.google.com/document/d/14JJPWtrFxkxzHa1NAmwzhTmeQO1vJtKDOJgBB_MPyfY/edit#) getting sentiment from all stakeholder groups good decisions might be made and when necessary ratified anonymously to prevent social pressure. Those without knowledge of an issue allow the delegate of their choice to vote on their behalf.

Not sure how that relates to this issue.

**Comment by fweilih** [comment]
Dear Jim, I agree with everything you say, I just think it may be incomplete. Allowing those without knowledge of an issue to allow a delegate of their choice to vote on their behalf is sensible; however, there must also be transparency surrounding the actions/decisions of the delegate to those who have delegated their authority, for such a system to be effective.  I am not sure this has been the case as surrounds the issues with Pithia (as you cite confidentiality) - hence I question the utility or purpose of gauging sentiment. The recent action relating to Pithia has far reaching consequences way beyond Pithia, in my view.  Will gauging uninformed sentiment fan the flames further or help bring about an objective and commercially reasonable way forward?

**Comment by jimscarver** [comment]
Yes, delegative democracy sentiment is an incomplete solution to making good decisions. It may be good for electing members of a working group. The working groups can then employ decision making best practices to resolve the issue. 

However, the elected members of a working group may not be the informed people capable of making the best decision. They are a team thrown together and may not be able to work together effectively or interact effectively with various other stakeholder working groups, committees and the board. They may not speak the same language., Guidance from the established organization is necessary to coordinate activities for them to be effective.

The [trust metric](https://github.com/rchain/bounties/wiki/Trust-Ratings) is designed to delegate power from the top down. This compliments bottom up liquid democracy. The differences in sentiment from the top and bottom both give weight to positions with a hope that resolving the differences might result in a better decision.

**Comment by jimscarver** [comment]
governance is off topic for this issue so I moved the discussion to the governance-colab discord channel.

**Comment by jimscarver** [comment]
It is not clear to me why we ought consider any rhoc invalid. I believe it is self defeating to do so. 
1. Surely any illegal gain from rhoc creates a liability for that gain giving us legal recourse.
2. That rhoc comes into the hands of people that did not purchase it from the coop seems unfair but it is not different from an airdrop. Airdrops can be very good in stimulating economic activity of a token and growth of a community. All that acquire rhoc become stakeholders in rchain and share our interests.
3. As we approach mainet and reveal the value of rchain a healthy rhoc market could allow us to be self funded by capital we minted ourselves.

If we believe in rchain then we cannot doubt the rhoc will have great value. We are shooting ourselves in the foot by killing the market.

**Comment by fweilih** [comment]
While I understand the need to respect confidentiality in certain delicate circumstances, I still find it problematic that we are trying to gauge sentiment with what seems to be a paucity of facts.  

Jim, are you able to confirm that legal action has indeed been filed or not?  If so, the pleadings (statement of claim filed by the plaintiff and statement of defence filed by the defendant) should be public record, so sharing those would not violate any issues of confidentiality.

Letting the membership 'hear both sides of the story' (and there are usually two sides to any contractual dispute) would provide more meaningful feedback on sentiment, in my humble opinion.

**Comment by fweilih** [comment]
I believe the Coop will want to continue to seek partnerships and enter legal agreements with different parties.  Will the spectre of RHOC paid as consideration becoming 'invalid' in case of a legal dispute,  deter future potential partners?  I think this needs to be considered by the membership.

**Comment by jimscarver** [comment]
Good point. In my view Rhoc received from the coop should always be honored so the rhoc that's part of a strategic partnership should never become invalid. That we have invalidated pithia rhoc presents an added risk of potential loss without just cause for prospective partners. Who would accept your money if you could invalidate it at will?

Partners that agree with our action may not be deterred but I do not think it makes strategic partnerships easier. 

In our agreements and public literature to have stated "all rhoc" can be converted to REV and it is not fair for us to go back on that promise for those who unwittingly bought invalid rhoc., Those who acquired the rhoc illegally are a different story but it is too easy for them to sell to the unsuspecting who would become victims of the coop if their hard earned rhoc was deemed worthless.

**Comment by dckc** [comment]
This is addressed as of Feb 14, 2020 when the mainnet wallets.txt was deployed.

References:

https://github.com/rchain/rchain/commit/cf10e26f537e516fb3ebcb5e9b9d77f1e0b907f0#diff-14230f61bd79457f34c0e11b9f121f6a (I note a couple edits since then; I don't think they suggest reconsidering this issue)
https://discordapp.com/channels/375365542359465989/454113117257859073/678444912827432969 my own endorsement of wallets.txt cf10e26
https://github.com/dckc/rbalance/blob/check_rev/TEST.rst 4b608c0 my audit
