### ISSUE TITLE
Development of an HR Strategy for the Coop

### ISSUE THREAD

**Issue by swanzer** [rchain-community/sm19a#13]
HR Strategy in Brief: 
1. Through Membership Survey, CV review, interviews and some job observation, get to know workforce Knowledge, Skills and Abilities (KSA’s).  What do we have in our tool kit today?
    * This is likely a subset result of a prerequisite Survey where Members are asked if they want to contribute in a workforce manner. Those who do are going to have to disclose some information about themselves in this area of their KSA’s. 
2. Have well defined business strategy, goals and objectives (long and short term, written out and mostly, SMART: Specific, Measurable, Attainable, Relevant, and Time specific. There can be audacious goals too, but those also need clarity and total commitment. 
3. Conduct analysis of Internal Strengths and Weaknesses and External Opportunities and Threats (SWOT analysis).  Some of this is already openly discussed (our internal weaknesses, but we need to get it on paper and then also be committed to taking action on it, or recognizing that it is just not going to be a strength of the organization and be okay with this fact.  i.e. Coke Cola is likely not strong at fruit juice based products and likely okay with it - so they buy a brand that is and adds it to their portfolio. 
4. Compare the KSA’s of current Workforce to the Strategy, Goals and Objectives.  Also review the Strengths, Weaknesses, Opportunities and Threats.  Make record of the Gaps, where the organization needs a development plan of its existing workforce, needs organizational changes, where opportunities are apparent, and develop an HR Workforce Strategy around all of this. (Get the Right People, Doing the Right Things, at the Right Time). 
5. Get management buy-in, specify the budget and get budget approval.
6. Develop Performance incentives tied to the execution of the strategy. (People and groups always work better towards rewards). 
7. Monitor the execution through specified Key Performance Indicators (KPI’s); in stated objectives, time tables, quality, quantity and budgets (Things that can be measured).

**Comment by dckc** [comment]
@swanzer is this FYI? Or is it a proposal that you are interested in collecting endorsement for?

It would perhaps be better re-organized as:
  - one issue on a member survey - i.e. #5
  - one issue on business strategy (which doesn't seem to be solely the purview of HR) - note overlap with #8, #2
  - ... perhaps some others

**Comment by richjensen3000** [comment]
@swanzer see Issue #5.  There is an existing survey (or at least framework) + @jimscarver has recommended integration with the bounty system. Perhaps you two can connect to assess these two resources, how they might be integrated, and recruit assistance from DiscordMembers?

**Comment by swanzer** [comment]
I will take a look at older survey's.  But we need to step back from the idea of integrating into an inactive program (Bounty) which is also not funded, and first be sure the Design of the overall strategy is well thought out, clearly defined, has stated goals and objectives, funded and agreed to.  I am aware of some of the different iterations of the bounty program; some was positive and some negative.  I was involved with clean up of invoices from the program late in 2018 and it was apparent to me there is room for improvement.  I think it's premature to say that the bounty program is the way.

**Comment by richjensen3000** [comment]
@swanzer Can you help produce an outline to Strategy etc? Maybe by the end of the week? Myself and others mentioned in this thread are here to help.

**Comment by swanzer** [comment]
@richjensen3000 What Nick @nmeyne has been working on in #8 is in the right direction.  If we boil it down, we need to fill in information along the following below.  Note that the Summary and Overview are largely for New Audiences such as a New Member, new Investor or someone who just needs a refresher.  The balance is what the coop body needs to review regularly (on a calendar time-table, such as Quarterly or Half Yearly) to report performance and adjust to internal and market conditions. (Also note, my background is in consumer products, so this may need changes to fit a software/tech organization. We had to review this basic structure each Quarter - except the first two, as we knew them inside and out).  This is the sort of thing though that any serious investor or dedicated member is going to want to see regularly). 

1. **Summary**: a brief, focused description of what we do and why we exist.  Include a snapshot of any projections that are key drivers (i.e. deliver 50,000 txs per second by 2020 and 100,000 by 2021).

2. **Coop Overview**: brief history of formation, why we are the type of organization we are and any noted successes to date. 

3. **Market and Customer description and analysis**: What's the market look like currently (who are the competitors)?  How does RChain fit into this market?  Who is the customer; describe them; their size, structure, what they are looking for and how we deliver what they need, uniquely; is it speed?  Security? What?  This is where we describe our points of differentiation from the market. 

4. **Marketing Plan**: What are the products and services we will deliver?  What are their costs?  Are these broken into differing channels depending on the customer?  How does our pricing compare to what others offer on the market? What are the revenue projections from each product?  What are the Promotion Plans for each major product, service or channel?  

5. **Operating Plan**:  Break down the daily functions that have to occur every day, such as Core Development, Marketing, Sales, Service, etc.  Describe the specific role each of these will play.  This will essentially describe how the organization will be structured.  Describe Operating Milestones which are the key objectives to be set for the organization.  Such as, "Be able to integrate a new dApp onto the platform within ___ days" or "Respond to platform performance problems within __ hours" or "Respond to any platform technical questions within __ minutes." Such objectives will flow outwardly from the sections above about why we exist and what we do, and will point us as to how we need to have resources aligned and funded to support these objectives.  These Operational Milestones will also be tracked, reported on regularly, consistently and scrubbed with a "fine tooth comb".  When they go well, they will be reason to celebrate and when they do not, they will keep people up at night. 

6. **Financial Plan**: Give clarity to the revenue model(s).  If there are different channels of revenue, detail each and what we are looking for them to deliver. Include a 3-5 year plan (which will be adjusted but still provides direction) Highlights will be brought to some (the BIG revenue makers) and others can be left grouped together in their respective category or however described (someone working responsibly for each channel will watch individual performance and report on them). The latest Income Statement, Balance Sheet and Cash Flow statement are included and each has a comparative measure to the same report and line as Last Year (or previous Quarter whichever is being reviewed).

**Comment by dckc** [comment]
@swanzer while I might have used a different issues list organization, I think your 1-6 list looks really good. Can you think of a useful next step?

The Summary (1) and Overview (2) belong on the web site, so they overlap with my interest in #4 .

**Comment by swanzer** [comment]
@dckc In brief, we need a series of meetings and a small team to do the work and get this written.  I think the probable contributors are pretty easy to identify, particularly those on Staff and Contracted, the Board Members and those actively involved with Committees.  I can create a Master Schedule: draft Attendees list, Agenda and pick some dates for discussions and target completion dates, and then share for editing and consensus to the plan.  How does this sound?

**Comment by dckc** [comment]
Sounds great; please do!

**Comment by dckc** [comment]
This no longer seems worth tracking as its own issue; it didn't make progress beyond a broad list of topics to a specific issue.
