### ISSUE TITLE
Governance Structure Review, IOB 4, GP001

### ISSUE THREAD

**Issue by nmeyne** [rchain-community/sm19a#3]
[polling](https://discordapp.com/channels/375365542359465989/393462637100400650/576781419347705857) based on https://github.com/rchain-community/sm19a/issues/3#issuecomment-489557345 below (TODO: copy it here.)

----
We could reconvene a Governance Committee meeting to consider / review proposals for the executive structure of the Coop.   Ideally, proposals for exec roles and their working groups should be submitted by the COO, but in principle any member can propose high level draft charters for new key roles / working groups to complement existing functioning groups - e.g. AFC and Gov Ctee - with existing charters.  Example new areas:  technical governance, commercial / ecosystem relations.......

Gov committee should then review and 'join up' proposals and propose a coherent overall structure to the membership.  Lightweight structure only - we don't have the funds for any bureaucracy!

**Comment by dckc** [comment]
@nmeyne care to refine this issue to any one or more specific parts?

This looks like a meta-issue: an issue about issues. Yes, we could review our governance structure. In fact, it looks to me like we are. The examples you give "technical governance, ..." belong as their own issues here, to my mind.

**Comment by dckc** [comment]
I'm inclined to narrow the scope of this to technical governance. I'll stand by for a bit to see what you think @nmeyne 

recall:

10:43 AM kellyfoster: ...I encourage those how are to keep in mind the critical role the coop plays in governing the platform once mainnet launches. 
https://github.com/rchain/legaldocs/blob/master/2018%20Annual%20Meeting/RChain%20Improvement%20Process%20(RIP%20Process).pdf was adopted as part of the vote of ballot measure #6 during the Oct 2018 annual meeting.

**Comment by nmeyne** [comment]
I agree there should be a focused effort on technical governance, as already agreed in actions for the last published Governance committee minutes.


I do not think this should be done in isolation, however.  It makes no sense to do tech gov in a silo, or where it is impossible to agree the relationships with other bodies, new or old, or to get its authority validated and endorsed.


You could say however that doing that 'big picture' review, joining up and proposing is business as usual for governance committee, and therefore doesn't need a motion.  The RIP process / commitee is already in the 'landscape' thing here:  https://docs.google.com/spreadsheets/d/1QkfB8rhTeQZ-KgWnqjl-B5VACtyMwQYtXuhId4TC0Uk/edit?usp=drivesdk


So you could narrow the scope if you like to emphasise the urgency and focus on tech governance, but IMHO leaving the big picture to business as usual will miss out on the opportunity here to put credible effort into fixing the busted roles and relationships, including the role of the President, who will otherwise continue with his business as usual.


Does that make sense?

- split, yes, but don't kill the parent process.


Nick

**Comment by dckc** [comment]
Issues are most useful if they get refined to proposals where, if lots of people said yes, something would be addressed. "Propose to review governance" is no different from the sm19a process itself, i.e. this whole issues list. It just brings us back to where we are.

For example, the role of the president is the subject of #2.

If you see other busted roles and relationships, please raise individual issues for them.

**Comment by nmeyne** [comment]
Many proposals could be created and several conflicting proposals could be adopted.  I thought SM19a was a democratic process that could commission some joined up 'design' of governance, which this issue was about.   I suppose I could raise issues for more or less every committee / role / body in https://docs.google.com/spreadsheets/d/1QkfB8rhTeQZ-KgWnqjl-B5VACtyMwQYtXuhId4TC0Uk/edit#gid=0   They are all broken/undefined.   I just thought that a bit 'reductionist' at this point?

**Comment by dckc** [comment]
So perhaps this is a matter of style.

But since you bring up democratic process, what yes / no question do you want to see lots of "yes"s to? As stated, it's "could we reconvene a Governance Committee meeting to consider / review proposals ...?" That seems like a straightforward question of fact: yes, of course we could.

**Comment by nmeyne** [comment]
At the moment, the Governance committee (and the membership) are largely ignored by the board. Governance committee is one of the committees, like the (dormant?) executive subservient to the President and the main board.  Two member observers attend the board meetings.  The intention was for the chair of gov cttee to be a board member and have a vote.  The then CEO and Chair of Gov Cttee - Kenny - resigned.  With no functioning influence on President or Board decisions, proposals for reform from the governance committee (see [GP001](https://docs.google.com/document/d/1nBRLjw8tuQd05GIacIhrN2FwFPJInwaiLNwiW0nb-E4/edit) = process to implement IoB4) were opposed by the President (in correspondence outside the board meeting) and have not been tabled for a formal vote by the board.

1. The board should approve GP001
2.  Governance Committee should continue to review the design of governance and propose improvements (with plans) under GP001..  to ensure proposed changes have transparency and support.
3. A governance committee member should attend board meetings and have voting rights...  and a member of the (tbd?) executive committee should serve on governance committee.

**Comment by dckc** [comment]
Thanks. That's more clear.

I might add ...

   1. The board should approve GP001 ... to fulfill its duty under 2018
   IOB4 member participation in governance.

**Comment by nmeyne** [comment]
+1 Thanks Dan

**Comment by dckc** [comment]
I see discussion of IOB 4 in the [Jun 4 board minutes](https://github.com/rchain/board/tree/master/2019/06-04):
> ... Steve Ross-Talbot has agreed to work with several members who have loosely formed a Working Group with the goal of formalizing and seating the Governance Committee. Evan Jensen commented that the Governance Committee will prepare, for the board's approval, the charters and procedures of all other Co-op Committees.

**Comment by dckc** [comment]
A governance committee charter was approved in the [2019-08-06 board meeting](https://github.com/rchain/board/tree/master/2019/08-06).

GP0001 was adopted by the membership in the [2019 Annual Meeting](https://github.com/rchain/legaldocs/tree/master/2019%20Annual%20Meeting)
