### ISSUE TITLE
Vacant Board Seat Nominations

### ISSUE THREAD

**Issue by richjensen3000** [rchain-community/sm19a#6]
There are three open seats. Do Members have nominees in mind or a process they would like to see implemented to fill these?

**Comment by dckc** [comment]
@richjensen3000 , I trust you're looking into some nomination ideas...

Until this includes one or two candidates, I'm unlikely to make it a priority in the agenda.

**Comment by richjensen3000** [comment]
@dckc Valid point!

**Comment by dckc** [comment]
The nominations are now in place:

- [CANDIDATE STATEMENTS FROM THE 2019 BOARD NOMINEES](https://blog.rchain.coop/blog/2019/10/08/candidate-statements-from-the-2019-board-nominees/) by RChain Staff | Oct 8, 2019
  - STEVE HENLEY
  - EVAN JENSEN
  - ERIC MENG
  - DARRYL NEUDORF
  - STEVE ROSS-TALBOT
  - DAN SALKOV
