### ISSUE TITLE
Bylaw Review and Revisions

### ISSUE THREAD

**Issue by richjensen3000** [rchain-community/sm19a#7]
Do Members have suggestions about decentralizing Executive functions in the Bylaws? Are there other matters that should be refined in the Bylaws? - Purview of the Governance Committee?

**Comment by dckc** [comment]
I suppose this captures a certain amount of the brainstorming discussion to date, but it should be refined and split into specific proposals.

@edeykholt offered some specific suggestions around 9:47am Kansas City time in last Saturday's office hours. I hope to review the discussion to recall the specifics:

https://youtu.be/x-YrKbdglnw
https://otter.ai/s/e52287f0b3e949ebbbb3f0e696afd8de

**Comment by dckc** [comment]
I'm reviewing these issues in preparation for the Oct 24 annual meeting. This issue hasn't catalyzed any particular proposals. Revising the bylaws is always a possibility, but this issue seems to be too general to be useful.
