### ISSUE TITLE
Operating Plans / Models

### ISSUE THREAD

**Issue by richjensen3000** [rchain-community/sm19a#8]
Nick Meynes has offered a rough revenue positive 24 Month Operating model for the Coop. It might be worthwhile for Members to evaluate it and consider generating further versions.

**Comment by dckc** [comment]
For reference, quoting Nick:

Rough Operating Plan from April 16:       "In answer to Greg’s challenge a while back for the community to come up with ‘any other ideas?’ I have drafted an ‘Alternative’ business plan for the RChain Coop.
It’s ‘Alt’ in the sense that we have heard a lot about the near term - RSong Special Purpose Vehicles and so on - and legal action to recover from past mistakes, but we haven’t seen much focused on the vision and future of the core platform….  The sort of thing that I think stakeholders….  Coop members, investors and partners want…   in a reasonably detailed and credible form.

To be clear, this is all guesswork.  It’s not endorsed by the board or anyone else.  It has some detail but I don’t know if it’s credible.   Credibility only comes through community insight, engagement and discussion.

Short video intro RChain Alt Business Plan - in 3:30:
https://youtu.be/yLm9-e9Yogc

The slide deck:
https://docs.google.com/presentation/d/1A8VtRfjxBZ_8InCxgfog3SzufbZo45t-OujZcJWQC-A/edit?usp=sharing

RChain Alt Business Plan - Summary
https://youtu.be/g2H62zTDXFk
30 mins

RChain Alt Business Plan - Forecast and Funding - Deep Dive
https://youtu.be/zGUvuJr3zvE
40 mins

Rchain Alt Business Plan - Approach - Deep Dive
https://youtu.be/KWbFs7O75Vs
40 mins

There is also an explanation and a link to this spreadsheet model in the slide deck:
https://docs.google.com/spreadsheets/d/19pagSV0BiVHpFap52WM3WW5-4fAT6i0jQXYdP2wjFtg/edit?usp=sharing


Enjoy.
" -- https://discordapp.com/channels/375365542359465989/406191011564617748/572283315776651305

**Comment by dckc** [comment]
@richjensen3000 effective proposals pretty much have to take the form of questions where, if lots of people said "yes," something useful would be put in motion. Do me a favor an spitball some questions of that form in this area? Even if they're not quite right, we can talk about what's not right about them and how to fix it.

cc @nmeyne

**Comment by swanzer** [comment]
I am happy to help with Operating Plans and Models.  I have experience in this area and the outcomes will directly impact #13  and any Workforce plans, roles, job descriptions, compensation planning, etc, etc.
