### ISSUE TITLE
divest from proprietary audio codec software license

### ISSUE THREAD

**Issue by richjensen3000** [rchain-community/sm19a#9]
This is a complex subject but also important because of its strategic position and the resources it occupies. Could this project benefit from consideration of a range of scenarios?

**Comment by dckc** [comment]
Suppose a lot of people answered "yes"; then what? I suspect "could this benefit from consideration ...?" isn't really the question you want answered. I trust you have one or two scenarios you are considering and will elaborate in due course.

Until this is more completely formed, I'm labelling it **help wanted** and **invalid** (not meant as a final judgement; just in the interest of clarity about which items I consider sufficiently well formed to be good use of meeting time).

**Comment by dckc** [comment]
I find myself persuaded by this argument:
> I think Rchain ceased to be 100% open source when the coop used nearly all of its funds on a proprietary software license.
> ...
> ... the second the majority of funds went to RSong, it ceased to be an open source blockchain project.

The coop should divest any significant interest in a proprietary software license.

@faddat I presume you're OK with my sharing your [comment of Apr 28 9:42 PM KC time in #members](https://discordapp.com/channels/375365542359465989/406191011564617748/572251277917028364) publicly.

**Comment by dckc** [comment]
Meredith announced in [RChain Community Debrief 133 Jun 19 at about 16:26][1] that the license agreement has been terminated. So (with a revised scope) this is done to my satisfaction.

[1]: https://youtu.be/sR-tPNhjNgc?t=986

cc @faddat
